language: php

notifications:
  email:
    recipients:
    - dmitriim@catalyst-au.net

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6

addons:
  postgresql: "9.3"

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
