language: php

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

dist: trusty

matrix:
  include:
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
